### ISSUE TITLE
It's hard to select the terms to be changed,

### ISSUE THREAD

**Issue by y503unavailable** [ishikawa999/redmine_message_customize#1]
Thank you for developing a useful plugin.
But there are points to be improved.

In the normal mode, if you enter a term, you can search as it is, 
but it will be mistaken as selection only from the display content.

I think it is better to change the display content below.

（In Japanese)
(before)「変更したい文言を選択してください。」
(after)「変更したい文言を選択、または入力してください。」

**Comment by y503unavailable** [comment]
As I noticed the search function of the target string, I corrected it.

**Comment by ishikawa999** [comment]
@y503unavailable

Thank you very much for the review.

> In the normal mode, if you enter a term, you can search as it is,
> but it will be mistaken as selection only from the display content.
> 
It's exactly as you said.

"変更したい文言を選択、または入力してください。(Please select or input the message you want to change.)" seems to have room for improvement.
In addition to the input, it is necessary to narrow down the choices by the input and select from them.

How about displaying a description of "検索ボックスにキーワードを入力することで、選択肢を絞り込むことが出来ます。(You can enter search terms in the search box to narrow down the results.)"?
<img width="581" alt="ScreenShot-2019-05-20-9 54 06" src="https://user-images.githubusercontent.com/14245262/57991130-d882de00-7ae7-11e9-9b01-b007b7443a45.png">

---

in japanese:
「変更したい文言を選択、または入力してください」と変更すると入力だけで動作が完結するように見えますが、
実際は入力によって選択肢を絞り込み、その中から選択するという動きが必要になります。
「キーワードを入力することで選択肢を絞り込むことが可能」という説明を表示するのはどうでしょうか？

**Comment by y503unavailable** [comment]
LGTM
> How about displaying a description of "検索ボックスにキーワードを入力することで、選択肢を絞り込むことが出来ます。(You can enter search terms in the search box to narrow down the results.)"

**Comment by ishikawa999** [comment]
I have committed this change. Thank you very much.
