### ISSUE TITLE
Select the current user's language by default in select#lang drop-down

### ISSUE THREAD

**Issue by vividtone** [ishikawa999/redmine_message_customize#27]
Currently, the default value for `select#lang` drop-down is always "en". I think it should be `User.current.language` or `Setting.default_language` because users want to customize messages of their own language in many cases.

![image](https://user-images.githubusercontent.com/114863/64095502-e8be8080-cd99-11e9-8b3b-44703157bef7.png)

**Comment by ishikawa999** [comment]
How to select the current default language:
`params[:lang].presence || User.current.language.presence || 'en'`

I am going to change it as below
`params[:lang].presence || @setting.custom_messages.keys.first || User.current.language.presence || Setting.default_language`

`@setting.custom_messages.keys.first` is one of the already customized languages.

**Comment by vividtone** [comment]
I found the condition that the problem occurs:

* The user's language setting is "(auto)".
* The locale determined by Accept-Language field in the HTTP request header is "ja"
* The dropdown's default language should be "ja" but actually it is "en" because User.current.language is blank (it means "auto").

I think using the current locale works better than using `@setting.custom_messages.keys.first`.

**Comment by ishikawa999** [comment]
Merged changes.
