### ISSUE TITLE
Option to temporarily disable customizes

### ISSUE THREAD

**Issue by vividtone** [ishikawa999/redmine_message_customize#3]
I hope the option to enable/disable customizes to be implemented.

Sometimes I want to compare a page with and without customizes. Currently, I have to copy and delete the customizes in YAML mode to achieve that.

I can see screens without customizes with only a few clicks if the feature is implemented.

**Comment by ishikawa999** [comment]
Implemented this feature.
Thank you for sharing your request.

<img width="731" alt="ScreenShot-2019-05-24-16 25 00" src="https://user-images.githubusercontent.com/14245262/58310020-a0113600-7e40-11e9-8f53-3464b73a9a16.png">
