### ISSUE TITLE
Menu item in the sidebar of admin page is not highlighted even when opening CustomMessageSettingsController#edit page

### ISSUE THREAD

**Issue by vividtone** [ishikawa999/redmine_message_customize#37]
The menu item in the sidebar is not highlighted.

![image](https://user-images.githubusercontent.com/114863/67739223-1f8cdc00-fa55-11e9-9b5f-3228f87fac7b.png)

I think it should be highlighted like View Customize.

![image](https://user-images.githubusercontent.com/114863/67739308-6975c200-fa55-11e9-9faa-608708adf7c6.png)

**Comment by ishikawa999** [comment]
Fixed by #39 and available from v0.1.1.
