### ISSUE TITLE
Plugin's message override seems not to work in Redmine 5.0 (zeitwerk)

### ISSUE THREAD

**Issue by sanak** [ishikawa999/redmine_message_customize#44]
I am trying to upgrade our existing Redmine system from Redmine 4.2 to 5.0, but I noticed that plugin's message override seems not to work as expected on our system.

I also noticed that the following test error on Redmine `5.0-stable` branch (with Ruby v2.7.5), so I think that something goes wrong...
```bash
% cp plugins/redmine_message_customize/35_change_load_order_locales.rb config/initializers/35_change_load_order_locales.rb
# :
% bundle exec rake redmine:plugins:test RAILS_ENV=test NAME=redmine_message_customize
Run options: --seed 54149

# Running:

...........................E

Error:
LocaleTest#test_available_messages_should_return_messages_without_plugin_messages_if_not_customizable_plugin_messages:
TypeError: no implicit conversion of String into Integer
    plugins/redmine_message_customize/lib/message_customize/locale.rb:21:in `block in reload!'
    plugins/redmine_message_customize/lib/message_customize/locale.rb:18:in `each'
    plugins/redmine_message_customize/lib/message_customize/locale.rb:18:in `reload!'
    plugins/redmine_message_customize/lib/message_customize/locale.rb:39:in `available_messages'
    plugins/redmine_message_customize/test/unit/lib/message_customize/locale_test.rb:57:in `test_available_messages_should_return_messages_without_plugin_messages_if_not_customizable_plugin_messages'


rails test plugins/redmine_message_customize/test/unit/lib/message_customize/locale_test.rb:51

...

Finished in 10.756975s, 2.8819 runs/s, 7.8089 assertions/s.
```

If more reproducible information is necessary, I will prepare it, so let me know about it.

Thanks,

**Comment by ishikawa999** [comment]
@sanak 
Thank you for sharing the issue.
I've been able to reproduce the issue and will investigate the cause.

**Comment by ishikawa999** [comment]
メモ:
35_change_load_order_localesがうまく機能していないため、プラグインの読み込み順がmessage_customizeより後のプラグインのメッセージ上書きができなくなっている。
（例: redmine_issue_templatesは上書きでき、view_customizeは上書きできないような感じ。名前の並びによる）

Redmine5.0からプラグインの読み込みタイミングが35_change_load_order_locales.rbの読み込みタイミングより後になったのが原因。
35_change_load_order_locales.rbを次のように更新すれば改善するはず。
```
# frozen_string_literal: true

Rails.application.config.to_prepare do
  if Redmine::Plugin.installed? :redmine_message_customize
    p = Redmine::Plugin.find(:redmine_message_customize)
    custom_locales = Dir.glob(File.join(p.directory, 'config', 'locales', 'custom_messages', '*.rb'))
    Rails.application.config.i18n.load_path = (Rails.application.config.i18n.load_path - custom_locales + custom_locales)
  end
end

```

Redmineのバージョンが5.0未満の時は元のコードのままで、5.0以上の場合は上のコードが動くようにすると良さそう
Rails.application.config.to_prepareで毎回動くのもどうかと思うので、初回だけ動くようにできたらさらに良い(もう少し調べる)

**Comment by ishikawa999** [comment]
Since the test failure seems to have another cause, we will split the issue #45.

**Comment by sanak** [comment]
@ishikawa999  
Thanks for quick answer and splitting the issue ! 🙇‍♂️ 
(迅速な回答と、Issueの切り分け、ありがとうございます！)

Redmine5.0での35_change_load_order_localesのタイミングに関しては、ご指摘の通り、名前順で後にくる、下記の `redmine_supply` プラグインの該当ブランチ(`feature/support-zeitwerk`)で発生していました。
https://github.com/gtt-project/redmine_supply/tree/feature/support-zeitwerk

上記の35_change_load_order_locales.rbの修正で、同様に上記プラグインの日本語が正しく変更されることを確認しましたので、合わせてご報告します。🙇‍♂️

**Comment by ishikawa999** [comment]
@sanak 

Thank you for confirming that 35_change_load_order_locales.rb works.

I have investigated and found that 35_change_load_order_locales.rb is not necessary in Redmine 4.2 or later by using the after_plugins_loaded hook, so I changed it (#49 ).

Could you please confirm that it works with the `support-redmine5.0 branch` (which now uses the after_plugins_loaded hook)? This is not urgent.

**Comment by sanak** [comment]
@ishikawa999  
Okay, thanks for quick fix!
I will check the PR branch on our environment within today, so please wait for a while. 🙇‍♂️

**Comment by sanak** [comment]
@ishikawa999  
I confirmed that the PR's `support-redmine5.0` branch works perfect without copying `35_change_load_order_locales.rb` on our Redmine 4.2 and 5.0 environment.

Thanks for the great work! 🙇‍♂️ 👍
