### ISSUE TITLE
Search box is not displayed after switching language

### ISSUE THREAD

**Issue by sk-ys** [ishikawa999/redmine_message_customize#50]
Search box is not displayed after switching language.

For example (default language: Japanese):
![image](https://user-images.githubusercontent.com/963792/171298810-1258f512-6c7f-48cc-ad48-7525fef779a0.png)

Environment:
- Redmine message customize plugin: 0.1.3
- Windows 10
- Redmine 5.0.0 (Bitnami Redmine Stack)
- Chrome 102.0.5005.63, Vivaldi

**Comment by ishikawa999** [comment]
@sk-ys 
Thanks for sharing the probrem.
I was able to reproduce the problem and have corrected it in https://github.com/ishikawa999/redmine_message_customize/pull/52.
Could you confirm that the problem has been resolved?

**Comment by sk-ys** [comment]
Thank you! The plugin is working fine.

**Comment by ishikawa999** [comment]
Thank you for your support.
I have created a release tag. https://github.com/ishikawa999/redmine_message_customize/releases/tag/0.1.4
