### ISSUE TITLE
Where to report security vulnerabilities?

### ISSUE THREAD

**Issue by liaham** [ishikawa999/redmine_message_customize#53]
Hi @ishikawa999,

I have found a potential security vulnerability in a third-party lib you are using. Where do you want me to report it? Do you have a dedicated email or should it go here?

Best Regards,
liaham

**Comment by ishikawa999** [comment]
@liaham 
Thank you for your report.
Could you please send an email to ishikawa@farend.jp ?

**Comment by ishikawa999** [comment]
@liaham 
I have responded to the problem you reported. https://github.com/farend/redmine_message_customize/releases/tag/0.1.5
Is it okay to close the issue?

**Comment by liaham** [comment]
@ishikawa999 
Thank yo very much for your fast response! 
The issue can be closed.

**Comment by ishikawa999** [comment]
@liaham 
Thank you very much!
