### ISSUE TITLE
Cannot customize Tamil language messages

### ISSUE THREAD

**Issue by vividtone** [ishikawa999/redmine_message_customize#60]
Redmine has added support for Tamil language in "r22357":https://www.redmine.org/projects/redmine/repository/svn/revisions/22357 but it seems that Message Customize does not support the new language.

Even if you add message customizes for Tamil languages, messages displayed on the screen don't change at all.

<img width="514" alt="圖片" src="https://github.com/farend/redmine_message_customize/assets/114863/4339dd5c-85bf-4be0-bc1a-9790832461ba">

**Comment by ishikawa999** [comment]
Thanks for reporting the issue.
Tamil language support with https://github.com/farend/redmine_message_customize/pull/61.
